### ISSUE TITLE
2.7.0 crashes infrequently on connect

### ISSUE THREAD

**Issue by Tharn** [equeim/tremotesf2#522] opened 2024-08-30 23:00 UTC
This can happen when starting the program, or when switching servers. It doesn't happen all the time but it happens regularly.

The connection itself, the populating of folders and trackers etc. seems to be very slow as well compared to the previous version.

**Comment by equeim** [comment] 2024-08-31 00:07
What distro and package (flatpak/native)?

**Comment by Tharn** [comment] 2024-08-31 00:14
Oh sorry, this is Windows 10 Pro x64.

**Comment by equeim** [comment] 2024-08-31 00:17
Interesting, I'm seeing some strange performance issues but can't reproduce crashes yet

**Comment by Tharn** [comment] 2024-08-31 00:27
I'm pretty sure that when it crashes, it doesn't produce a .log either. Will keep an eye on it.

**Comment by equeim** [comment] 2024-08-31 00:51
Does it get better for you if you disable sidebar (in the View menu)?

**Comment by toniexly** [comment] 2024-09-02 16:28
I can confirm this. and the window often freezes, and the response is slow when I click.

**Comment by equeim** [comment] 2024-09-02 17:06
> I can confirm this. and the window often freezes, and the response is slow when I click.

Do you experience crashes too?

**Comment by toniexly** [comment] 2024-09-02 17:51
> > I can confirm this. and the window often freezes, and the response is slow when I click.
> 
> Do you experience crashes too?

sometimes the window would disappear(close itself?) when trying to connect...

**Comment by equeim** [comment] 2024-09-04 20:52
@Tharn @toniexly Could you try to reproduce the crash in this build (preferably Debug one): https://github.com/equeim/tremotesf2/releases/tag/crash-test

It should show additional info on the crash

**Comment by Tharn** [comment] 2024-09-04 21:05
I tried with the crash test build, it seems to be faster populating the left sidebar again but I managed to produce a crash after many starts. Will try with the debug symbols next.


![error](https://github.com/user-attachments/assets/dcf852c6-ced7-4a7b-8011-efb39097bd46)

**Comment by Tharn** [comment] 2024-09-05 17:23
Grab the Debug Symbols version and try to reproduce that crash.

**Comment by equeim** [comment] 2024-09-06 00:03
> ## Fatal error
> 
> Press Ctrl+C to copy this report
> 
> FATAL ERROR: std::terminate called
> 
> Unhandled C++ exception: std::bad_alloc: bad allocation
> 
> PDB file does not exist at expected path C:/Green Software/Tremotesf/tremotesf.pdb, not reporting stack trace
> ## 确定

That looks like a different crash than one I just fixed. However I would need a stack trace from debug build to figure out anything

**Comment by toniexly** [comment] 2024-09-06 08:39
> > ## Fatal error
> > Press Ctrl+C to copy this report
> > FATAL ERROR: std::terminate called
> > Unhandled C++ exception: std::bad_alloc: bad allocation
> > PDB file does not exist at expected path C:/Green Software/Tremotesf/tremotesf.pdb, not reporting stack trace
> > ## 确定
> 
> That looks like a different crash than one I just fixed. However I would need a stack trace from debug build to figure out anything

![剪贴板图片](https://github.com/user-attachments/assets/b37ceeef-e6a8-47b8-946e-1cdd44ef9ac1)

**Comment by equeim** [comment] 2024-09-06 12:09
> > > ## Fatal error
> > > Press Ctrl+C to copy this report
> > > FATAL ERROR: std::terminate called
> > > Unhandled C++ exception: std::bad_alloc: bad allocation
> > > PDB file does not exist at expected path C:/Green Software/Tremotesf/tremotesf.pdb, not reporting stack trace
> > > ## 确定
> > 
> > That looks like a different crash than one I just fixed. However I would need a stack trace from debug build to figure out anything
> 
> ![剪贴板图片](https://github.com/user-attachments/assets/b37ceeef-e6a8-47b8-946e-1cdd44ef9ac1)
> 

Ok, now it's the crash that I have seen. IDK where std::bad_alloc came from, I think I will go ahead with releasing 2.7.1 for now

**Comment by toniexly** [comment] 2024-09-06 13:25
> > > > ## Fatal error
> > > > Press Ctrl+C to copy this report
> > > > FATAL ERROR: std::terminate called
> > > > Unhandled C++ exception: std::bad_alloc: bad allocation
> > > > PDB file does not exist at expected path C:/Green Software/Tremotesf/tremotesf.pdb, not reporting stack trace
> > > > ## 确定
> > > 
> > > 
> > > That looks like a different crash than one I just fixed. However I would need a stack trace from debug build to figure out anything
> > 
> > 
> > ![剪贴板图片](https://private-user-images.githubusercontent.com/37370944/365095791-b37ceeef-e6a8-47b8-946e-1cdd44ef9ac1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjcwNTksIm5iZiI6MTcyNTYyNjc1OSwicGF0aCI6Ii8zNzM3MDk0NC8zNjUwOTU3OTEtYjM3Y2VlZWYtZTZhOC00N2I4LTk0NmUtMWNkZDQ0ZWY5YWMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDEyNDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZjgzZDJlOTkyNzc1NjRlNDgxZTNhNzE0NjBjMGM5NmJjNjgzYjJiNGJkNDU1ODM0OWJmZDg1NmQ4NjI2NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TXo0ZKLJi83V931oXNwbQlX7SdYIFj6A20_W68_9AmQ)
> 
> Ok, now it's the crash that I have seen. IDK where std::bad_alloc came from, I think I will go ahead with releasing 2.7.1 for now
I switch back to 2.7 crash test version. it seems working fine now...IDK what changes i've made...:0)

**Comment by Tharn** [comment] 2024-09-06 16:15
Maybe that other crash you caught is more rare. The one with the log you gave is very common so it is much more likely to get caught.

**Comment by equeim** [comment] 2024-09-14 22:23
Should be fixed now

**Closed by equeim** 2024-09-14 22:23 UTC
