### ISSUE TITLE
Tremotesf flatpak crashes with clicking the  "adding torrent file" button

### ISSUE THREAD

**Issue by rezad1393** [equeim/tremotesf2#478] opened 2024-03-22 12:54 UTC
running in flatpak 
`flatpak run org.equeim.Tremotesf`

crashing and gives this error after clicking the button

```
tremotesf: Connected
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
tremotesf: Disconnected

```

p.s.:
forgot to add that this happens with latest version and I didn't notice it with older versions.

adding torrent from file manager works. it is only when adding files from the app that opens mini file manager that crash happens.

p.p.s:
I don't know what the etiquette for adding more info that should have already been in first post to an already posted first post is.
so I use p.p......s for it.
if there is another way tell me or should I not touch the first one and add more info in later posts.

**Comment by bassstorm** [comment] 2024-03-22 12:57
Oh, I encountered that as well on Flatpak install (Debian 12, KDE).
Quick solution was to delete app settings folder completely and configure from scratch.

**Comment by bassstorm** [comment] 2024-03-22 13:45
Well, I was just in a need to fix it "here and now" :) So I've deleted whole `~/.var/app/org.equeim.Tremotesf`. Don't have a backup to troubleshoot it further, sorry.
But hopefully my report will help author or others to find out the root cause quicker.

**Comment by equeim** [comment] 2024-03-22 23:05
I can't reproduce the crash locally. If you can make it crash again could you please install debug symbols (`flatpak install --include-debug org.equeim.Tremotesf`) and post the crash stacktrace from journalctl? You will need to rollback to previous version using `flatpak update --commit=475882348d11f3cc378161bf4ca1d37d51f8b9e40766242041247247993fd69e org.equeim.Tremotesf` command and delete the config beforehand.

FYI you can also list all available versions using `flatpak remote-info --log flathub org.equeim.Tremotesf` command.

**Comment by bassstorm** [comment] 2024-03-22 23:12
@equeim just a quick extra note: the issue appeared with update to latest release. I've been using the app for about a year long, with only specific config of mapped folders (which didn't work for me anyway), but manual removal of those mappings via UI didn't help. Hence complete fresh config choice.

**Comment by rezad1393** [comment] 2024-03-22 23:40
it happened for me too with my new update in flatpak.
by removing that file I mentioned it went away.

it didnt happen with last version.

and I can't "post crash stacktrace from journalctl"
how do I do that? 
journalctl from host doesnt show anything.

**Comment by equeim** [comment] 2024-03-23 02:12
Actually the information about previous crash should be recorded. Does `coredumpctl -1 info tremotesf` output anything?

If not then:
1. Downgrade tremotesf via `flatpak update --commit=475882348d11f3cc378161bf4ca1d37d51f8b9e40766242041247247993fd69e org.equeim.Tremotesf` (you may need to run that as root)
2. Delete/move config
3. Run tremotesf, do something like adding torrent so that some config values will be saved
4. Update tremotesf and install debug symbols: `flatpak update org.equeim.Tremotesf && flatpak install --include-debug org.equeim.Tremotesf`
5. Run Tremotesf again and try to crash it

Crash info should appear in `coredumpctl -1 info tremotesf` and system logs (`journalctl --boot --pager-end`). Your distro/DE may also have GUI application to view crashes.

**Comment by rezad1393** [comment] 2024-03-23 14:30
I dont have to go back to older version.
I can recreate the crash right now

after crashing I dont get anything in "coredumpctl -1 info tremotesf" 

and in journalctl --boot --pager-end I get the app messages but I already included them at the top:

```
tremotesf: Connected
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
tremotesf: Disconnected
```

**Comment by rezad1393** [comment] 2024-03-23 14:31
I am inclined to close this issue because in a new install it would not happen but it is up to developer.

**Comment by armerpunkt** [comment] 2024-03-29 05:25
I was getting the same issue with the latest flatpak version too. I deleted my config and initially that fixed the problem but then it came back. I thought maybe it's a permissions issue with flatpak, so I installed the OpenSUSE Tumbleweed version that is listed and had a similar thing happen there. So it's not flatpak specific.

However, I have been able to figure out what is causing the issue (reproducible both with flatpak and OpenSUSE Tumbleweed builds): Uncheck "Show icon in the notification area" in the options.  Try to add a torrent file and it will crash. Recheck "Show icon in the notification area" it works again.

**Comment by rezad1393** [comment] 2024-03-29 16:23
can confirm the  "Show icon in the notification area" issue here too.
archlinux flatpak version.

**Comment by bassstorm** [comment] 2024-03-29 21:35
Thanks @armerpunkt! I can confirm your findings here as well on Debian 12 KDE.

**Comment by equeim** [comment] 2024-03-30 02:43
Thanks, it seems to be some weird bug in KDE: https://bugs.kde.org/show_bug.cgi?id=483439

Fortunately there is a workaround.

**Comment by bassstorm** [comment] 2024-03-30 08:53
Just for the record, I experience that problem on KDE5.

**Comment by equeim** [comment] 2024-04-06 17:05
Should be fixed in the latest version.

**Closed by equeim** 2024-04-06 17:05 UTC
