### ISSUE TITLE
Crash on open Torrent's preferences

### ISSUE THREAD

**Issue by vladest** [equeim/tremotesf2#539] opened 2024-10-14 19:33 UTC
Ubuntu 24.04 amd64
When opening any torrent's preferences, got a crash
traps: tremotesf[53014] general protection fault ip:5e4d0afed058 sp:7fff3a591c70 error:0 in tremotesf[148058,5e4d0aee3000+12e000]

**Comment by equeim** [comment] 2024-10-20 01:44
Can't reproduce it in VM.

Did you install it from Flathub or deb repo? (if repo then make sure that you changed 23.10 to 24.04 in download.opensuse.org urls. I should probably modify instruction so that it is done automatically).

Also do you use vanilla Ubuntu with GNOME and Wayland?

**Comment by equeim** [comment] 2024-10-20 10:32
> > Can't reproduce it in VM.
> > 
> > Did you install it from Flathub or deb repo? (if repo then make sure that you changed 23.10 to 24.04 in download.opensuse.org urls. I should probably modify instruction so that it is done automatically).
> > 
> > Also do you use vanilla Ubuntu with GNOME and Wayland?
> 
> Hello
> I'm on Kubuntu 24.10
> the URL in the apt source file is: URIs: http://download.opensuse.org/repositories/home:/equeim:/tremotesf/Debian_12/

You should use Ubuntu repo instead: `deb http://download.opensuse.org/repositories/home:/equeim:/tremotesf/xUbuntu_24.04/ /`

Ubuntu and Debian are not guaranteed to be compatible with each other.

**Comment by moonraker2** [comment] 2024-10-30 21:30
I'm seeing the crash when opening torrent properties on flatpak version of tremotesf. 
My OS is Debian 12.

**Comment by equeim** [comment] 2024-11-04 21:46
> I'm seeing the crash when opening torrent properties on flatpak version of tremotesf. My OS is Debian 12. DE is Plasma and X.org display server.
> 
> The crash happens consistently :)

Does it happen for any torrent or specific ones?
I can't reproduce it in VM.

Please try the following:
1. Install `libflatpak-dev` package
2. Run `flatpak install --include-sdk org.equeim.Tremotesf`
3. Then run `flatpak-coredumpctl -m tremotesf --gdb-arguments '--batch --ex bt' org.equeim.Tremotesf`
4. 
This should print the stack trace of a crash.

**Comment by moonraker2** [comment] 2024-11-08 21:33
Sorry for taking a while to respond, but yes, it happens whenever trying to access properties of any torrent.

I followed the steps you laid out, which led to this:

`➜  ~ flatpak-coredumpctl -m tremotesf --gdb-arguments '--batch --ex bt' org.equeim.Tremotesf
Executable /usr/bin/tremotesf doesn't seem to be a flatpaked application.
Running: `"flatpak" "run" "--filesystem=home" "--filesystem=/tmp" "--command=gdb" "--devel" "org.equeim.Tremotesf" "/usr/bin/tremotesf" "/tmp/tmpse0c5lld" "--batch" "--ex" "bt"`
error: app/org.equeim.Tremotesf/x86_64/master not installed
Traceback (most recent call last):
  File "/usr/bin/flatpak-coredumpctl", line 83, in <module>
    coredumper.run()
  File "/usr/bin/flatpak-coredumpctl", line 58, in run
    subprocess.check_call(flatpak_command)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['flatpak', 'run', '--filesystem=home', '--filesystem=/tmp', '--command=gdb', '--devel', 'org.equeim.Tremotesf', '/usr/bin/tremotesf', '/tmp/tmpse0c5lld', '--batch', '--ex', 'bt']' returned non-zero exit status 1.
`
Is that what you were looking for?

**Comment by equeim** [comment] 2024-11-09 20:21
No, flatpak tells that Tremotesf is not installed. What does `flatpak list --all` show?

**Comment by moonraker2** [comment] 2024-11-09 21:44
Not sure what has happened. When I went to the Software center and looked up tremotesf, it was indeed showing as not installed, so I went ahead and reinstalled it, then ran the coredumpctl command again, which gave me this:

Executable /usr/bin/tremotesf doesn't seem to be a flatpaked application.
Running: `"flatpak" "run" "--filesystem=home" "--filesystem=/tmp" "--command=gdb" "--devel" "org.equeim.Tremotesf" "/usr/bin/tremotesf" "/tmp/tmpmadj1y0b" "--batch" "--ex" "bt"`
error: runtime/org.kde.Sdk/x86_64/6.7 not installed
Traceback (most recent call last):
  File "/usr/bin/flatpak-coredumpctl", line 83, in <module>
    coredumper.run()
  File "/usr/bin/flatpak-coredumpctl", line 58, in run
    subprocess.check_call(flatpak_command)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['flatpak', 'run', '--filesystem=home', '--filesystem=/tmp', '--command=gdb', '--devel', 'org.equeim.Tremotesf', '/usr/bin/tremotesf', '/tmp/tmpmadj1y0b', '--batch', '--ex', 'bt']' returned non-zero exit status 1.


Seems the same error as before.

Running flatpak list --all gives me this:

Tremotesf                                org.equeim.Tremotesf                            2.7.2                      stable        system
Tremotesf debug symbols                  org.equeim.Tremotesf.Debug                                                 stable        system

**Comment by equeim** [comment] 2024-11-09 23:43
Run `flatpak install org.kde.Sdk//6.7`, for some reason it wasn't installed automatically by `--include-sdk` flag.

If it wasn't installed through flatpak, maybe you also have it installed from as deb?

**Comment by moonraker2** [comment] 2024-11-10 00:56
Nope, it was definitely installed as flatpak :)

I ran flatpak install org.kde.Sdk//6.7 and re-ran "flatpak-coredumpctl -m tremotesf --gdb-arguments '--batch --ex bt' org.equeim.Tremotesf" which had quite a different result  - ending with a segfault in that app:
 https://pastebin.com/qVa9iPSw

**Comment by moonraker2** [comment] 2024-11-10 01:05
But uhh.. now I can in fact open torrent properties.... Not sure what has resolved it :)
I proceeded to remove the sdk and dev/debug packages, then reinstalled tremotesf for good measure, and it is still working fine when accessing torrent properties.
As such, I think my problem is resolved - thanks a lot for helping me sort it out.

**Comment by equeim** [comment] 2024-11-12 23:14
I think I finally tracked down the issue, it's a bug in GCC 12 (fixed in https://github.com/gcc-mirror/gcc/commit/58a7b1e354530d8dfe7d8fb859c8b8b5a9140f1f). It should not be reproducible with Flatpak package since it uses newer GCC. But Debian 12 package from OBS repo is affected.

**Comment by equeim** [comment] 2024-11-20 19:04
Should be fixed in 2.7.3

**Closed by equeim** 2024-11-20 19:04 UTC
